# schedules: 
#   - cron: "0,3,6,9,12,15,18,21,24,28,32,36,39,42,45,48,51,54,57 * * * *"
#     displayName: Daily midnight build
#     branches:
#       include:
#       - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo $(date)
  displayName: 'Run a multi-line script'
