# This is a basic workflow to help you get started with Actions

name:
  Deploy_ACU1_BRW_HAA_RG_D3
  # Triggers the workflow on push or pull request events but only for the main branch
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  # push:
  #   branches: [dev]
  # pull_request:
  #   branches: [dev]

  workflow_dispatch:

env:
  APP: HAA
  ENV: D3
  PREFIX: ACU1
  SecretName: ACU1_BRW_HAA_RG_D3

jobs:
  EnvironmentDeploy:
    runs-on: windows-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # Add wait on concurrent workflows executing via https://github.com/marketplace/actions/action-turnstyle
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACU1_BRW_HAA_RG_D3 }}
          enable-AzPSSession: true

      - name: ${{ env.ENV }}_RG
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            echo ${{ env.SecretName }}
            dir env:
          azPSVersion: latest
